### PR TITLE
Test to reproduce #143

### LINKED ISSUE #143: Extract fails on array properties with class constant keys
Version: 4.1.1

### Bug Description
If a class property is an array and the default value uses class constants as keys, extracting the class throws a `TypeError: Illegal offset type`

### Steps To Reproduce
```
	class Class1
	{
		public $constKey = [self::class => 'foo'];
	}
```

### Expected Behavior
The property is extracted.

### Possible Solution
This was broken by something around https://github.com/nette/php-generator/commit/d915b7fa643cd0cf6ffe306c25ac5c3db24914a4#diff-634a48b3c9efd3101dad0b38a2be84c212cdf9d9e73246cf36de82e6e26a876eR424-R426

I'll do a PR with a test to reproduce and see If I can figure out a fix.

### PR DESCRIPTION
**Pull request by kynx**
- bug fix #143
- BC break? no

This PR adds a test to reproduce #143. Not sure if I'm asserting the right thing, but I'll update it if I can figure out a fix.

### CODE REVIEW

**Comment by kynx** [comment]
Actually I have no idea what should be done here.

Maybe detect if the array contains and keys with an `Identifier` for a name and then return a `Literal()` for the whole thing, like It did before 4.1.1? That seems kind of kludgy, but it is what I have to do when generating these arrays. @dg any suggestions?

**Comment by kynx** [comment]
@dg I don't know what to do here. That [commit](https://github.com/nette/php-generator/commit/d915b7fa643cd0cf6ffe306c25ac5c3db24914a4#diff-634a48b3c9efd3101dad0b38a2be84c212cdf9d9e73246cf36de82e6e26a876eR424-R426) is a major BC break for me. Should I revert the whole thing or are there bits that don't break stuff for people?

**Comment by dg** [comment]
Probably the best way, given backwards compatibility, is to just return the whole array as Literal, the way it used to work…

**Comment by kynx** [comment]
👍 Many thanks for that!

**Pull request closed without merging**
