### PR TITLE
WIP: add php8 support

### PR DESCRIPTION
**Pull request by ChrisB9**
- bug fix & new feature for php 8.0
- BC break? yes
(all changes here will break support for tests below 7.4, might require a 4.0)

(using php 8.0alpha3 with this container: https://hub.docker.com/r/chrisb9/php8-nginx-xdebug)

I started on the new php 8.0 features and realized, that a bunch of things won't work anymore with the new version.

Todos:
- [x] Union-Type Support
- [ ] Exceptions in arrow-functions and after nullables
- [x] Attribute-Support (unable to implement until syntax is clear)
- [x] comma-support at the end of method-signatures
- [x] constructor property promotion (that one is super useful for generated classes)
- [x] static return type
- [x] mixed return type

(i hope i didnt forget anything?)

This is still a draft, because I still have issues fixing this problem here:
`-- FAILED: Nette\PhpGenerator generator. | ClassType.from.phpt
   Exited with error code 255 (expected 0)
   E_DEPRECATED: Required parameter $c follows optional parameter $a`

### CODE REVIEW

**Comment by dg** [comment]
Great! I fixed tests so they all pass on PHP 8 nightly https://travis-ci.org/github/nette/php-generator/jobs/713438049

**Comment by ChrisB9** [comment]
Thanks, that's perfect. I'll merge it back into my branch.
Since union types are currently the only supported in phpstorm, I'll start with that.

**Comment by ChrisB9** [comment]
Should we use this and create a new version of php-generator and drop therefore php 7.1 support or do we try to keep compatibility?

**Comment by dg** [comment]
It would definitely be better to try to maintain compatibility.

**Comment by dg** [comment]
PHP 8 support is done in v3.5

**Pull request closed without merging**
