### PR TITLE
Fixed mixed implicit nullability (closes #74)

### LINKED ISSUE #74: Incorrect method property mixed type generated from reflection
Version: 3.5.1

### Bug Description
```php
class SomeClass {
  public function something(mixed $param) {}
}

// ClassType::withBodiesFrom(SomeClass::class) generates:

class SomeClass {
  public function something(?mixed $param) {}
}
```

which is incorrect as `null` is implicitly contained in `mixed`.

image

### PR DESCRIPTION
**Pull request by dakur**
- bug fix for #74
- BC break? no

### CODE REVIEW

**Comment by dakur** [comment]
Not sure if more places are affected, I've fixed only this one.

**Comment by dg** [comment]
It will probably also apply to properties and return values, right?

Will it work with uppercase 'MIXED'?

**Comment by dakur** [comment]
> It will probably also apply to properties and return values, right?
> 
> Will it work with uppercase 'MIXED'?

Frankly said, I have no idea. 🤷‍♂️ I just wanted to sketch where the problem lies and what looks like solution. But I don't know the code base much (or at all), so I rather pass it on people more familiar with it.

**Comment by dg** [comment]
fixed

**Comment by dakur** [comment]
Aha, there should be probably ` ! strcmp()` in here: https://github.com/nette/php-generator/blob/41dcc5d1cb322835e5950a76515166c90923c6b7/src/PhpGenerator/Printer.php#L296

**Comment by dakur** [comment]
@dg Ok, it works, sorry, I've screwed up my `expected` test file during previous testing.

**Pull request closed without merging**
