### PR TITLE
Add possibility to configure wrapping length of Dumper-class

### LINKED ISSUE #55: Add possibility to configure wrapping length of Dumper-class
Please see #45 

To add the possibility of "wrap always", it will be necessary to add public static variable $wrapAlways into the Dumper class and use it here https://github.com/nette/php-generator/blame/master/src/PhpGenerator/Dumper.php#L115

### PR DESCRIPTION
**Pull request by duxthefux**
Closes #55

- new feature #55 
- BC Break: no

See #45 and #55

### CODE REVIEW

**Comment by duxthefux** [comment]
Please note that static getter and setter was added to force type safety

**Comment by dg** [comment]
Thanks for PR.

I have this thing on the TODO list. However, the solution is not so simple, because it is not possible to use static variables in Nette (because it follows the principles of dependency injection).

So this will be a little harder to solve. I'll leave it open so far.

**Comment by duxthefux** [comment]
hey @dg,

any update on this? 
As far as I can see it no dependency injection via nette container is used for the `Dumper`-class currently. So maybe it's not that tragic to use a static property now, as a lot of refactoring needs to be done anyways to get rid of calls like `(new Dumper)->format($code, ...$args)`.

Happy to hear your opinion.

**Comment by dg** [comment]
Printer has new property $wrapLength

**Pull request closed without merging**
