### PR TITLE
Add failing test for array

### PR DESCRIPTION
**Pull request by Nek-**
- bug fix (that is only bug exposition ATM)
- BC break? no

Hello, I found this bug :(.

### CODE REVIEW

**Comment by dg** [comment]
I can't see it.

**Comment by Nek-** [comment]
@dg what can't you see?

I was not able to make a good fix for it :/.

**Comment by JanTvrdik** [comment]
The current behavior is intentional. See https://github.com/nette/php-generator/blob/fd5e55cdd652efbce5878a4d56584059bd9b0802/src/PhpGenerator/Dumper.php#L102

**Comment by dg** [comment]
Ok I get it. But it's not a bug, just a cosmetic thing because `[606990006 => 'bar', 606990007 => 'baz']` is the same as `[606990006 => 'bar', 'baz']`.

**Comment by Nek-** [comment]
@dg absolutely. But this is also assuming PHP behaves like that, which is weird. And I think all weird stuff should not be considered as "this is good".

Of course, it's also extremely disturbing for people that will use generated classes, that's mostly why I'm suggesting to support this.

**Comment by dg** [comment]
I would not call it a weird, it is a documented standard behavior that I like to use, for example in `$months = [1 => 'January', 'February', 'March', 'April', 'May', 'June', ...]`. But I understand that in the dumps where most keys are present, the missing ones are confusing.

**Pull request closed without merging**
